# Generated by Django 5.2.3 on 2025-06-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_room_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
