# Generated by Django 5.2.3 on 2025-06-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_chat_room_name_chat_is_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default='message', max_length=20),
        ),
    ]
